# Sync-Project-Brains.ps1
# Bidirectional sync between a central Obsidian "brain" vault and each repo's .brain/ folder.
#
# Files in .brain/  (bridge between the vault and the project agent)
# ┌─────────────────┬──────────────┬──────────────────────────────────┐
# │ File            │ Direction    │ Source of truth                  │
# ├─────────────────┼──────────────┼──────────────────────────────────┤
# │ CONTEXT.md      │ vault → repo │ Projects/<Name>.md               │
# │ TASKS.md        │ vault → repo │ ## Brain → Repo · Tasks          │
# │ ASKS.md         │ vault → repo │ ## Brain → Repo · Asks           │
# │ INSTRUCTIONS.md │ vault → repo │ Templates/Brain-INSTRUCTIONS.md  │
# │ STATUS.md       │ repo → vault │ frontmatter parsed               │
# │ LOG.md          │ repo → vault │ append to ## Log                 │
# │ ANSWERS.md      │ repo → vault │ merged into Q → A: in source     │
# └─────────────────┴──────────────┴──────────────────────────────────┘
#
# Generic / portable: NOTHING is hardcoded. Pass -BrainRoot (or set $env:BRAIN_PATH)
# and optionally -ReposRoot (or $env:BRAIN_REPOS_ROOT). Idempotent.
#
#   pwsh Sync-Project-Brains.ps1 -BrainRoot "D:/Vaults/Brain"
#   pwsh Sync-Project-Brains.ps1                       # uses $env:BRAIN_PATH
#   pwsh Sync-Project-Brains.ps1 -DryRun               # preview only

[CmdletBinding()]
param(
    [string]$BrainRoot = $env:BRAIN_PATH,
    [string]$ReposRoot = $env:BRAIN_REPOS_ROOT,
    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'

if (-not $BrainRoot) {
    throw "BrainRoot not set. Pass -BrainRoot <vault path> or set the BRAIN_PATH environment variable."
}
$BrainRoot = (Resolve-Path $BrainRoot).Path
if (-not $ReposRoot) { $ReposRoot = Split-Path -Parent $BrainRoot }   # default: vault's parent folder

#─────────────────────────────────────────────────────────────────────
# Helpers
#─────────────────────────────────────────────────────────────────────

function Get-Frontmatter {
    param([string]$Path)
    if (-not (Test-Path $Path)) { return @{} }
    $text = Get-Content $Path -Raw
    if ($text -notmatch '(?s)^---\s*\r?\n(.*?)\r?\n---') { return @{} }
    $block = $Matches[1]
    $fm = @{}
    foreach ($line in $block -split "`n") {
        if ($line -match '^\s*([A-Za-z0-9_-]+):\s*(.*?)\s*$') {
            $fm[$Matches[1]] = $Matches[2].Trim().Trim('"')
        }
    }
    return $fm
}

function Get-Section {
    param([string]$Text, [string]$Heading)
    if ($Text -match "(?ms)^##\s+$([regex]::Escape($Heading))\s*\r?\n(.*?)(?=^##\s+|\z)") {
        return $Matches[1].TrimEnd()
    }
    return ''
}

function Resolve-RepoFolder {
    param([string]$ProjectPath, [string]$FolderField)
    if (-not $FolderField) { return $null }
    $base = Split-Path -Parent $ProjectPath
    try {
        $abs = [System.IO.Path]::GetFullPath([System.IO.Path]::Combine($base, $FolderField))
        if (Test-Path $abs -PathType Container) { return $abs }
    } catch { }
    return $null
}

#─────────────────────────────────────────────────────────────────────
# PUSH builders (vault → repo)
#─────────────────────────────────────────────────────────────────────

function Build-Context {
    param([string]$ProjectPath)
    $fm = Get-Frontmatter $ProjectPath
    $name = (Split-Path -Leaf $ProjectPath) -replace '\.md$',''
    $raw = Get-Content $ProjectPath -Raw
    $scope      = Get-Section $raw 'Scope'
    $milestones = Get-Section $raw 'Milestones'
    $team       = Get-Section $raw 'Team'
    $generatedAt = (Get-Date).ToString('yyyy-MM-dd HH:mm')
    $sourcePath = (Join-Path $BrainRoot "Projects/$name.md") -replace '\\','/'

    return @"
---
# AUTO-GENERATED by brain sync — do not edit. Edit $sourcePath instead.
project: $name
synced-at: $generatedAt
phase: $($fm.phase)
priority: $($fm.priority)
status: $($fm.status)
attention: $($fm.attention)
next-milestone: $($fm.'next-milestone')
next-milestone-label: $($fm.'next-milestone-label')
brain-source: "$sourcePath"
---

# $name — Brain Context

> **READ-ONLY.** Snapshot from the central brain. Change scope/milestones/team at the source.

## Scope
$scope

## Milestones
$milestones

## Team
$team

## How to interact with the brain
See ``.brain/INSTRUCTIONS.md`` for protocol. TL;DR: read this + ``TASKS.md`` + ``ASKS.md``, work, write ``STATUS.md`` + append ``LOG.md`` + answer ``ANSWERS.md``.

## Brain link
- Project note: ``$sourcePath``
"@
}

function Build-Tasks {
    param([string]$ProjectPath)
    $name = (Split-Path -Leaf $ProjectPath) -replace '\.md$',''
    $raw = Get-Content $ProjectPath -Raw
    $tasksSection = Get-Section $raw 'Brain → Repo · Tasks'
    if (-not $tasksSection) { return $null }
    $generatedAt = (Get-Date).ToString('yyyy-MM-dd HH:mm')
    return @"
---
# AUTO-GENERATED. Tick a box here OR in the vault — sync reconciles both ways.
project: $name
synced-at: $generatedAt
---

# Tasks from the brain

> The central brain delegated these tasks to the agent in this repo.
> Tick the checkbox when you finish one; the next sync reflects it back.
> If a task is no longer relevant, leave it ticked + add a note in ``LOG.md``.

$tasksSection
"@
}

function Build-Asks {
    param([string]$ProjectPath)
    $name = (Split-Path -Leaf $ProjectPath) -replace '\.md$',''
    $raw = Get-Content $ProjectPath -Raw
    $asksSection = Get-Section $raw 'Brain → Repo · Asks'
    if (-not $asksSection) { return $null }
    $generatedAt = (Get-Date).ToString('yyyy-MM-dd HH:mm')
    return @"
---
project: $name
synced-at: $generatedAt
---

# Asks from the brain

> Open questions for the repo agent. Write answers in ``ANSWERS.md`` (one per question).
> Leave the Q here; the brain pairs Q→A on next sync.

$asksSection
"@
}

function Build-Instructions {
    param([string]$ProjectName)
    $tplPath = Join-Path $BrainRoot 'Templates/Brain-INSTRUCTIONS.md'
    if (Test-Path $tplPath) {
        return (Get-Content $tplPath -Raw) -replace '\{\{PROJECT\}\}', $ProjectName
    }
    return $null
}

#─────────────────────────────────────────────────────────────────────
# PULL parsers (repo → vault)
#─────────────────────────────────────────────────────────────────────

function Read-NewLogEntries {
    param([string]$LogPath, [string]$BrainProjectPath)
    if (-not (Test-Path $LogPath)) { return @() }
    $repoLogLines = @(Get-Content $LogPath | Where-Object { $_ -match '^\s*-\s' })
    $brainLog = Get-Section (Get-Content $BrainProjectPath -Raw) 'Log'
    $new = @()
    foreach ($line in $repoLogLines) {
        $key = ($line -replace '\s+', ' ').Trim()
        if ($key.Length -gt 60) { $key = $key.Substring(0, 60) }
        if (-not ($brainLog -match [regex]::Escape($key))) { $new += $line }
    }
    return $new
}

function Read-TaskCompletions {
    param([string]$TasksPath)
    if (-not (Test-Path $TasksPath)) { return @() }
    $done = @()
    foreach ($line in (Get-Content $TasksPath)) {
        if ($line -match '^\s*-\s*\[(x|X)\]\s*(.+?)\s*$') { $done += $Matches[2].Trim() }
    }
    return $done
}

function Read-Answers {
    param([string]$AnswersPath)
    if (-not (Test-Path $AnswersPath)) { return @() }
    $text = Get-Content $AnswersPath -Raw
    $pairs = @()
    $rx = [regex]'(?ms)^Q:\s*(.+?)\r?\n\s*A:\s*(.+?)(?=^Q:|\z)'
    foreach ($m in $rx.Matches($text)) {
        $pairs += [pscustomobject]@{
            Question = $m.Groups[1].Value.Trim()
            Answer   = $m.Groups[2].Value.Trim()
        }
    }
    return $pairs
}

#─────────────────────────────────────────────────────────────────────
# WRITER into vault project notes
#─────────────────────────────────────────────────────────────────────

function Update-BrainProject {
    param(
        [string]$BrainProjectPath,
        [hashtable]$StatusUpdates,
        [array]$NewLogEntries,
        [array]$CompletedTasks,
        [array]$Answers
    )
    $text = Get-Content $BrainProjectPath -Raw

    foreach ($key in @('phase','progress','last-activity')) {
        if ($StatusUpdates -and $StatusUpdates.ContainsKey($key) -and $StatusUpdates[$key]) {
            $pattern = "(?m)^$([regex]::Escape($key)):\s*.*$"
            if ($text -match $pattern) { $text = [regex]::Replace($text, $pattern, "${key}: $($StatusUpdates[$key])") }
        }
    }
    if ($NewLogEntries -and $NewLogEntries.Count -gt 0) {
        $appendBlock = ($NewLogEntries -join "`n") + "`n"
        $text = [regex]::Replace($text, '(?m)^(##\s+Log\s*\r?\n)', "`$1$appendBlock")
    }
    if ($CompletedTasks -and $CompletedTasks.Count -gt 0) {
        foreach ($t in $CompletedTasks) {
            $escapedTask = [regex]::Escape($t)
            $text = $text -replace "(?m)^(\s*-\s*\[)\s(\]\s*$escapedTask\s*$)", "`$1x`$2"
        }
    }
    if ($Answers -and $Answers.Count -gt 0) {
        foreach ($qa in $Answers) {
            $escapedQ = [regex]::Escape($qa.Question)
            $pattern = "(?m)^(\s*-\s*Q:\s*$escapedQ)\s*$"
            $replacement = "`$1`n  → A: $($qa.Answer -replace "`n", ' ')"
            if ($text -match $pattern) { $text = [regex]::Replace($text, $pattern, $replacement) }
        }
    }
    Set-Content -Path $BrainProjectPath -Value $text -Encoding UTF8
}

#─────────────────────────────────────────────────────────────────────
# Main loop
#─────────────────────────────────────────────────────────────────────

$projDir = Join-Path $BrainRoot 'Projects'
if (-not (Test-Path $projDir)) { throw "No Projects/ folder under BrainRoot: $projDir" }
$projectFiles = Get-ChildItem -Path $projDir -Filter '*.md' -Recurse | Where-Object { $_.BaseName -ne '_INDEX' }
$count = 0; $pushed = 0; $pulled = 0

foreach ($pf in $projectFiles) {
    $fm = Get-Frontmatter $pf.FullName
    if ($fm.status -eq 'archived') { Write-Host "[$($pf.BaseName)] skipped (archived)"; continue }
    if ($fm.type   -eq 'admin')    { Write-Host "[$($pf.BaseName)] skipped (admin)";    continue }
    if ($fm.type   -eq 'legacy')   { Write-Host "[$($pf.BaseName)] skipped (legacy)";   continue }

    $repoFolder = Resolve-RepoFolder -ProjectPath $pf.FullName -FolderField $fm.folder
    if (-not $repoFolder) { continue }

    $brainDir = Join-Path $repoFolder '.brain'
    $contextP = Join-Path $brainDir 'CONTEXT.md'
    $tasksP   = Join-Path $brainDir 'TASKS.md'
    $asksP    = Join-Path $brainDir 'ASKS.md'
    $instrP   = Join-Path $brainDir 'INSTRUCTIONS.md'
    $statusP  = Join-Path $brainDir 'STATUS.md'
    $logP     = Join-Path $brainDir 'LOG.md'
    $answersP = Join-Path $brainDir 'ANSWERS.md'

    $count++
    $name = $pf.BaseName
    Write-Host "[$name] repo=$repoFolder"

    if (-not (Test-Path $brainDir)) {
        if ($DryRun) { Write-Host "  (dry-run) would create $brainDir" }
        else { New-Item -ItemType Directory -Path $brainDir | Out-Null; Write-Host "  created $brainDir" }
    }

    # ── PUSH down ──
    $newCtx   = Build-Context      -ProjectPath $pf.FullName
    $newTasks = Build-Tasks        -ProjectPath $pf.FullName
    $newAsks  = Build-Asks         -ProjectPath $pf.FullName
    $newInstr = Build-Instructions -ProjectName $name

    if (-not $DryRun) {
        Set-Content -Path $contextP -Value $newCtx -Encoding UTF8
        if ($newTasks) { Set-Content -Path $tasksP -Value $newTasks -Encoding UTF8 }
        if ($newAsks)  { Set-Content -Path $asksP  -Value $newAsks  -Encoding UTF8 }
        if ($newInstr -and -not (Test-Path $instrP)) { Set-Content -Path $instrP -Value $newInstr -Encoding UTF8 }
        if (-not (Test-Path $statusP)) {
            Set-Content -Path $statusP -Value "---`nproject: $name`nlast-activity:`nprogress:`nphase:`nblockers: []`nnext-action:`n---`n`n# Current Status`n`n> Update this when something changes. The brain reads it on sync.`n" -Encoding UTF8
        }
        if (-not (Test-Path $logP))     { Set-Content -Path $logP     -Value "# Activity Log`n`n> Append-only. ``- YYYY-MM-DD HH:MM — [TYPE] description``  (TYPES: WORK · DECISION · MILESTONE · BLOCKER · LESSON · HANDOFF)`n" -Encoding UTF8 }
        if (-not (Test-Path $answersP)) { Set-Content -Path $answersP -Value "# Answers to Brain Asks`n`n> Format per answer:`n>`n> ``Q: <verbatim question from ASKS.md>``  `n> ``A: <your answer>``  `n>`n> The next sync pairs your A back to the question in the vault note.`n" -Encoding UTF8 }
        $pushed++
    }

    # ── PULL up ──
    $statusUpdates  = Get-Frontmatter $statusP
    $newLog         = Read-NewLogEntries -LogPath $logP -BrainProjectPath $pf.FullName
    $completedTasks = Read-TaskCompletions -TasksPath $tasksP
    $answers        = Read-Answers -AnswersPath $answersP

    $brainTaskSection = Get-Section (Get-Content $pf.FullName -Raw) 'Brain → Repo · Tasks'
    $alreadyTicked = @()
    foreach ($line in $brainTaskSection -split "`n") {
        if ($line -match '^\s*-\s*\[(x|X)\]\s*(.+?)\s*$') { $alreadyTicked += $Matches[2].Trim() }
    }
    $newlyCompleted = $completedTasks | Where-Object { $_ -notin $alreadyTicked }

    if ($statusUpdates.Count -gt 0 -or $newLog.Count -gt 0 -or $newlyCompleted.Count -gt 0 -or $answers.Count -gt 0) {
        if ($DryRun) {
            Write-Host "  (dry-run) would pull: status=$($statusUpdates.Count) log=$($newLog.Count) ticked=$($newlyCompleted.Count) ans=$($answers.Count)"
        } else {
            Update-BrainProject -BrainProjectPath $pf.FullName `
                -StatusUpdates $statusUpdates -NewLogEntries $newLog `
                -CompletedTasks $newlyCompleted -Answers $answers
            $pulled++
            Write-Host "  pulled: status=$($statusUpdates.Count) log+$($newLog.Count) ticked+$($newlyCompleted.Count) answered+$($answers.Count)"
        }
    }
}

#─────────────────────────────────────────────────────────────────────
# Auto-discovery: find .brain/ folders up to 3 levels deep under ReposRoot
# that aren't linked from any project note yet. Auto-create the note.
#─────────────────────────────────────────────────────────────────────

$discovered = 0
$projectTpl = Join-Path $BrainRoot 'Templates/Project.md'

$linkedFolders = @{}
foreach ($pf in $projectFiles) {
    $rf = Resolve-RepoFolder -ProjectPath $pf.FullName -FolderField (Get-Frontmatter $pf.FullName).folder
    if ($rf) { $linkedFolders[$rf.TrimEnd('\','/').ToLower()] = $pf.FullName }
}

$brainCandidates = Get-ChildItem -Path $ReposRoot -Directory -Filter '.brain' -Recurse -Depth 3 -ErrorAction SilentlyContinue |
    Where-Object { $_.FullName -notlike "$BrainRoot*" }   # exclude the vault itself

foreach ($bc in $brainCandidates) {
    $hostRepo = (Split-Path -Parent $bc.FullName).TrimEnd('\','/')
    if ($linkedFolders.ContainsKey($hostRepo.ToLower())) { continue }

    $candidateName = Split-Path -Leaf $hostRepo
    $slug = $candidateName -replace '[^A-Za-z0-9_\-]', '-'
    $newProjectPath = Join-Path $projDir "$slug.md"
    if (Test-Path $newProjectPath) {
        Write-Host "[discover] $candidateName -> note exists ($slug.md) but folder field doesn't match. Skipping."
        continue
    }

    $relPath = (Resolve-Path -Relative -LiteralPath $hostRepo -RelativeBasePath $projDir -ErrorAction SilentlyContinue)
    if (-not $relPath) { $relPath = "$hostRepo" }

    $tpl = if (Test-Path $projectTpl) { Get-Content $projectTpl -Raw } else { "---`ntype:`nstatus: planning`nfolder: `"$relPath`"`n---`n`n# $candidateName`n" }
    $tpl = $tpl -replace '\{\{title\}\}', $candidateName
    $tpl = $tpl -replace '\{\{date\}\}', (Get-Date -Format 'yyyy-MM-dd')
    $tpl = $tpl -replace '(?m)^folder:\s*.*$', "folder: `"$relPath`""

    if ($DryRun) { Write-Host "[discover] would create $newProjectPath (host: $hostRepo)" }
    else { Set-Content -Path $newProjectPath -Value $tpl -Encoding UTF8; Write-Host "[discover] created note: $slug.md -> $hostRepo"; $discovered++ }
}

Write-Host ""
Write-Host "[sync] scanned $count linked projects · pushed $pushed · pulled $pulled · discovered $discovered orphan .brain folders"
if ($discovered -gt 0) { Write-Host "[sync] re-run me to push CONTEXT/TASKS/ASKS to newly-discovered projects" }
